#!/bin/bash

# Prerequisites for ESP-IDF
if [[ "$OSTYPE" == "darwin"* ]]; then
  brew install cmake ninja dfu-util ccache python3
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  sudo apt install git wget flex bison gperf python3 python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0 -y
fi

mkdir -p ~/esp
git clone --recursive https://github.com/espressif/esp-idf.git ~/esp/esp-idf
cd ~/esp/esp-idf

./install.sh esp32c3

echo -e "Run export.sh to begin development:\n. $HOME/esp/esp-idf/export.sh"
